### ISSUE TITLE
PHP Fatal error:  Trait 'Illuminate\Database\Eloquent\SoftDeletingTrait' not found

### ISSUE THREAD

**Issue by edstevo** [asposeforcloud/asposelaravel#1]
Immediately after installing via composer, all of the SoftDelete functionality implemented in my applications break.

It returns this message: PHP Fatal error:  Trait 'Illuminate\Database\Eloquent\SoftDeletingTrait' not found

Then, after removing the dependencies from composer and running composer update (i.e. deleting) the soft deletes work again.

So, I'm assuming that this package is causing them to break?

**Comment by masood-anwer** [comment]
I am checking this issue and keep you updated once done with it.

**Comment by edstevo** [comment]
Great.

I look forward to the result!

Many thanks,

Ed Stephenson
T: +447724302647
E: edward.stephenson@me.com

**Comment by masood-anwer** [comment]
I have looked into it but our package does not produce this issue. Our package doesn't perform any database operations. 

I have checked the reason of this issue, mostly users faced issue after upgrading framework. You may visit these links:
https://github.com/barryvdh/laravel-ide-helper/issues/83
http://stackoverflow.com/questions/24949655/what-causes-the-error-not-found-softdeletingtrait-class
https://laracasts.com/forum/?p=1766-laravel-4-2-soft-deletes-issue/0
